/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedShoppingRouteImport } from './routes/_authenticated/shopping'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRecurringRouteImport } from './routes/_authenticated/recurring'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedInflationRouteImport } from './routes/_authenticated/inflation'
import { Route as AuthenticatedInflationRouteImport } from './routes/_authenticated/inflation'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedConsumptionRouteImport } from './routes/_authenticated/consumption'
import { Route as AuthenticatedBudgetsRouteImport } from './routes/_authenticated/budgets'
import { Route as AuthenticatedCategoryKeyRouteImport } from './routes/_authenticated/category.$key'
import { Route as AuthenticatedBillIdRouteImport } from './routes/_authenticated/bill.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShoppingRoute = AuthenticatedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecurringRoute = AuthenticatedRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInflationRoute = AuthenticatedInflationRouteImport.update({
  id: '/inflation',
  path: '/inflation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInflationRoute = AuthenticatedInflationRouteImport.update({
  id: '/inflation',
  path: '/inflation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsumptionRoute =
  AuthenticatedConsumptionRouteImport.update({
    id: '/consumption',
    path: '/consumption',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoryKeyRoute =
  AuthenticatedCategoryKeyRouteImport.update({
    id: '/category/$key',
    path: '/category/$key',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillIdRoute = AuthenticatedBillIdRouteImport.update({
  id: '/bill/$id',
  path: '/bill/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/consumption': typeof AuthenticatedConsumptionRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inflation': typeof AuthenticatedInflationRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/inflation': typeof AuthenticatedInflationRoute
  '/recurring': typeof AuthenticatedRecurringRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/search': typeof AuthenticatedSearchRoute
  '/shopping': typeof AuthenticatedShoppingRoute
  '/bill/$id': typeof AuthenticatedBillIdRoute
  '/category/$key': typeof AuthenticatedCategoryKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/consumption': typeof AuthenticatedConsumptionRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inflation': typeof AuthenticatedInflationRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/inflation': typeof AuthenticatedInflationRoute
  '/recurring': typeof AuthenticatedRecurringRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/search': typeof AuthenticatedSearchRoute
  '/shopping': typeof AuthenticatedShoppingRoute
  '/bill/$id': typeof AuthenticatedBillIdRoute
  '/category/$key': typeof AuthenticatedCategoryKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRoute
  '/_authenticated/consumption': typeof AuthenticatedConsumptionRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inflation': typeof AuthenticatedInflationRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/inflation': typeof AuthenticatedInflationRoute
  '/_authenticated/recurring': typeof AuthenticatedRecurringRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/shopping': typeof AuthenticatedShoppingRoute
  '/_authenticated/bill/$id': typeof AuthenticatedBillIdRoute
  '/_authenticated/category/$key': typeof AuthenticatedCategoryKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/budgets'
    | '/consumption'
    | '/history'
    | '/home'
    | '/inflation'
    | '/insights'
    | '/inflation'
    | '/recurring'
    | '/reports'
    | '/scan'
    | '/search'
    | '/shopping'
    | '/bill/$id'
    | '/category/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/budgets'
    | '/consumption'
    | '/history'
    | '/home'
    | '/inflation'
    | '/insights'
    | '/inflation'
    | '/recurring'
    | '/reports'
    | '/scan'
    | '/search'
    | '/shopping'
    | '/bill/$id'
    | '/category/$key'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/budgets'
    | '/_authenticated/consumption'
    | '/_authenticated/history'
    | '/_authenticated/home'
    | '/_authenticated/inflation'
    | '/_authenticated/insights'
    | '/_authenticated/inflation'
    | '/_authenticated/recurring'
    | '/_authenticated/reports'
    | '/_authenticated/scan'
    | '/_authenticated/search'
    | '/_authenticated/shopping'
    | '/_authenticated/bill/$id'
    | '/_authenticated/category/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shopping': {
      id: '/_authenticated/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthenticatedShoppingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recurring': {
      id: '/_authenticated/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AuthenticatedRecurringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inflation': {
      id: '/_authenticated/inflation'
      path: '/inflation'
      fullPath: '/inflation'
      preLoaderRoute: typeof AuthenticatedInflationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inflation': {
      id: '/_authenticated/inflation'
      path: '/inflation'
      fullPath: '/inflation'
      preLoaderRoute: typeof AuthenticatedInflationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consumption': {
      id: '/_authenticated/consumption'
      path: '/consumption'
      fullPath: '/consumption'
      preLoaderRoute: typeof AuthenticatedConsumptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/category/$key': {
      id: '/_authenticated/category/$key'
      path: '/category/$key'
      fullPath: '/category/$key'
      preLoaderRoute: typeof AuthenticatedCategoryKeyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bill/$id': {
      id: '/_authenticated/bill/$id'
      path: '/bill/$id'
      fullPath: '/bill/$id'
      preLoaderRoute: typeof AuthenticatedBillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRoute
  AuthenticatedConsumptionRoute: typeof AuthenticatedConsumptionRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInflationRoute: typeof AuthenticatedInflationRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedInflationRoute: typeof AuthenticatedInflationRoute
  AuthenticatedRecurringRoute: typeof AuthenticatedRecurringRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedShoppingRoute: typeof AuthenticatedShoppingRoute
  AuthenticatedBillIdRoute: typeof AuthenticatedBillIdRoute
  AuthenticatedCategoryKeyRoute: typeof AuthenticatedCategoryKeyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRoute,
  AuthenticatedConsumptionRoute: AuthenticatedConsumptionRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInflationRoute: AuthenticatedInflationRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedInflationRoute: AuthenticatedInflationRoute,
  AuthenticatedRecurringRoute: AuthenticatedRecurringRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedShoppingRoute: AuthenticatedShoppingRoute,
  AuthenticatedBillIdRoute: AuthenticatedBillIdRoute,
  AuthenticatedCategoryKeyRoute: AuthenticatedCategoryKeyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
